############################################################
USERS
############################################################
GET http://localhost:8080/api/user/check/ankittanna@hotmail.com

############################################################

POST http://localhost:8080/api/user/register
content-type: application/json

{
  "username": "ankittanna11@hotmail.com",
  "password": "TMSPortal@123",
  "registrationDate": "Sun Nov 29 2020 11:21:33 GMT+0530 (India Standard Time)",
  "subscriptionStartDate": "Sun Nov 29 2020 11:21:33 GMT+0530 (India Standard Time)",
  "subscriptionEndDate": "Sun Nov 29 2020 11:21:33 GMT+0530 (India Standard Time)",
  "isPremiumMember": false,
  "premiumMembershipReferenceId": "NA",
  "companyName": "Abt SLB",
  "address": "G2-102 PA Pune",
  "panCardNumber": "ABCD4444D",
  "mobileNumber": "9049772849"
}

############################################################

POST http://localhost:8080/api/user/login
content-type: application/json

{
  "username": "ankittanna5@hotmail.com",
  "password": "TMSPortal@123"
}
############################################################

POST http://localhost:8080/api/user/refresh-token

############################################################

DELETE http://localhost:8080/api/user/logout

############################################################

GET http://localhost:8080/api/auth/generateKey

############################################################

GET http://localhost:8080/api/share/stakeholders/ankittanna11@hotmail.com
Content-Type: application/json

############################################################

PUT http://localhost:8080/api/share/add-stakeholder
Content-Type: application/json

{
  "owner": "ankittanna5@hotmail.com",
  "stakeholders": [
    {
      "name": "Roop Bansal",
      "mobileNumber": "9948594839",
      "description": "CTO",
      "isBlocked": false
    }
  ]
}

############################################################

DELETE http://localhost:8080/api/share/delete-stakeholder
Content-Type: application/json

{
  "owner": "ankittanna11@hotmail.com",
  "mobileNumber": "9228839283"
}

############################################################

PUT http://localhost:8080/api/share/block-stakeholder
Content-Type: application/json

{
  "owner": "ankittanna11@hotmail.com",
  "mobileNumber": "9228839283",
  "isBlocked": false
}

############################################################
# GET ALL TENDERS - ADMIN ONLY
GET http://localhost:8080/api/tenders/all
Content-Type: application/json

############################################################
# GET ALL TENDERS BY USERNAME - Owner check with token
GET http://localhost:8080/api/tenders/all/ankittanna5@hotmail.com
Content-Type: application/json

############################################################
# GET TENDERS BY USERNAME - Owner check with token
GET http://localhost:8080/api/tenders/all-tenders/ankittanna5@hotmail.com
Content-Type: application/json

############################################################

# CREATE TENDER
POST  http://localhost:8080/api/tenders
Content-Type: application/json

{
    "name": "My Tender 6",
    "amount": "100000",
    "fee": "100",
    "emd": "ARZ123",
    "referenceNumber": "ABC123",
    "tenderId": "11232221234",
    "publishedDate": "Thu Dec 17 2020 21:28:06 GMT+0530 (India Standard Time)",
    "bidDueDate": "Thu Dec 17 2020 21:28:06 GMT+0530 (India Standard Time)",
    "bidCutOffTime": "1608220716288",
    "userKeyName": "abtanna",
    "userLoginId": "ankittanna",
    "userPassword": "Ankit@123",
    "userWebsite": "http://www.ankit.com",
    "properties": {
      "owner": "ankittanna6@hotmail.com",
      "createdDate": "Thu Dec 17 2020 21:28:06 GMT+0530 (India Standard Time)",
      "document": "http://www.documents/mydoc.pdf",
      "isDeleted": false,
      "isComplete": false,
      "isNotFilled": false
    }
}

############################################################

# DELETE TENDER
DELETE  http://localhost:8080/api/tenders/delete/5fdb8b4271595b296132f7fb
Content-Type: application/json

############################################################

# RETRIEVE TENDER
GET  http://localhost:8080/api/tenders/retrieve/5fdb8b4271595b296132f7fb
Content-Type: application/json

############################################################

# DELETE TENDER PERMANENTLY
DELETE  http://localhost:8080/api/tenders/delete-permanently/5fdf572be0f8ba362cfe3551
Content-Type: application/json

############################################################

# UPDATE TENDER
PUT  http://localhost:8080/api/tenders/update/5fdf6080bb69093da73dea4c
Content-Type: application/json

{
  "properties": {
    "owner": "ankittanna5@hotmail.com",
    "createdDate": "Thu Dec 17 2020 21:28:06 GMT+0530 (India Standard Time)",
    "document": "http://www.documents/mydoc.pdf",
    "isDeleted": false,
    "isComplete": false,
    "isNotFilled": false
  },
  "_id": "5fdf6080bb69093da73dea4c",
  "name": "My Tender 2 XYZ",
  "amount": "100000",
  "fee": "100",
  "emd": "ARZ123",
  "referenceNumber": "ABC123",
  "tenderId": "11232221234",
  "publishedDate": "Thu Dec 17 2020 21:28:06 GMT+0530 (India Standard Time)",
  "bidDueDate": "Thu Dec 17 2020 21:28:06 GMT+0530 (India Standard Time)",
  "bidCutOffTime": "1608220716288",
  "userKeyName": "abtanna",
  "userLoginId": "ankittanna",
  "userPassword": "Ankit@123",
  "userWebsite": "http://www.ankit.com",
  "__v": 0
}
